### ISSUE TITLE
a problem with interpolation

### ISSUE THREAD

**Issue by Gue3bara** [Gue3bara/Cairo#7]
@davelab6 I'm working on interpolating some extra weights now 
adding ExtraLight, Light, Regular, SemiBold, Bold & black
i have a problem with U+062C 
the central dot in the black weight intersects with the base line as you can see bellow
<img width="1230" alt="screenshot 2016-03-07 05 26 27" src="https://cloud.githubusercontent.com/assets/12478169/13560244/aa2cf2ae-e425-11e5-8350-73bacfe76344.png">
what can be the solution for such issue?
do i have to redesign the glyph?

**Comment by Gue3bara** [comment]
right now I'm done with all the compatibility issues for the arabic and doing some final rechecking 
but i find compatibility issues with the latin 
<img width="1654" alt="screenshot 2016-03-07 05 38 40" src="https://cloud.githubusercontent.com/assets/12478169/13560372/fe79208e-e426-11e5-912d-f6265534dc7d.png">

what should i do about that?
is it related to transforming the ttx latin to ufo?

**Comment by davelab6** [comment]
Which latin source file did you start with exactly? 

For 062C you'll need a bracket master

**Comment by davelab6** [comment]
https://glyphsapp.com/tutorials/additional-masters-for-individual-glyphs-the-brace-trick

**Comment by Gue3bara** [comment]
The latin is from the github 
https://github.com/librefonts/titilliumweb
will check on that trick

**Comment by davelab6** [comment]
Ah, that is not a good source. I will likely remove all that librefonts thing, it was a test that didn't really work out. The TTX files are just the TTF files, and I just converted them from the OTFs (which is bad) so when you imported those, the result will not be good.

www.campivisivi.net/titillium/ is the project homepage but it doesn't seem to have VFBs. 

So we need to contact the designers to request their VFB/etc original source files.

**Comment by Gue3bara** [comment]
I remember when i 1st started i somehow i was directed to the github as the
main page for the project
lets wait for the original source files and then figure out the replacement
will be working on arabic for the current time

On Mon, Mar 7, 2016 at 6:51 PM, Dave Crossland notifications@github.com
wrote:

> Ah, that is not a good source. I will likely remove all that librefonts
> thing, it was a test that didn't really work out. The TTX files are just
> the TTF files, and I just converted them from the OTFs (which is bad) so
> when you imported those, the result will not be good.
> 
> www.campivisivi.net/titillium/ is the project homepage but it doesn't
> seem to have VFBs.
> 
> So we need to contact the designers to request their VFB/etc original
> source files.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gue3bara/Cairo/issues/7#issuecomment-193341292.

## 

Mohamed Gaber | محمد جابر
http://portfolio.gaberism.net/
MN: +20 100 332 4822 | Blog: www.gaberism.net
Skype: che.guebara | Twitter: @Gue3bara http://twitter.com/Gue3bara

**Comment by davelab6** [comment]
@Gue3bara is this fixed with https://github.com/Gue3bara/Cairo/commit/6240123dcdac3a0b17ce910875861735c71a2f9b ?

**Comment by Gue3bara** [comment]
<img width="1684" alt="screenshot 2016-03-12 05 40 31" src="https://cloud.githubusercontent.com/assets/12478169/13720784/cd6a49f8-e81a-11e5-9bc2-ba82057d77a2.png">
<img width="1585" alt="screenshot 2016-03-12 05 40 50" src="https://cloud.githubusercontent.com/assets/12478169/13720785/cd6d19a8-e81a-11e5-8fcf-e1d98ab021f6.png">

came across this issue now and reported it to the forum 
https://forum.glyphsapp.com/t/problem-with-interpolation-arabic/4055
do you have any idea what could be causing this?

**Comment by davelab6** [comment]
Does it existing the exported TTFs?

On 11 March 2016 at 23:23, Mohamed Gaber notifications@github.com wrote:

> [image: screenshot 2016-03-12 05 40 31]
> https://cloud.githubusercontent.com/assets/12478169/13720784/cd6a49f8-e81a-11e5-9bc2-ba82057d77a2.png
> [image: screenshot 2016-03-12 05 40 50]
> https://cloud.githubusercontent.com/assets/12478169/13720785/cd6d19a8-e81a-11e5-8fcf-e1d98ab021f6.png
> 
> came across this issue now and reported it to the forum
> do you have any idea what could be causing this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Gue3bara/Cairo/issues/7#issuecomment-195657908.

## 

Cheers
Dave

**Comment by Gue3bara** [comment]
ehm 
nope!

**Comment by Gue3bara** [comment]
The connecting problem is a bug with Glyphs and they figured it out and working on solving it 
for the current time they recommend "disable the two eye icons in the layer panel"
which still doesn't solve the problem

**Comment by davelab6** [comment]
;)

**Comment by Gue3bara** [comment]
All interpolation issues solved for both arabic and latin
